apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-server
  name: secret-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: secret-server
    spec:
      containers:
        - name: redis
          image: redis:6
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 64Mi
        - name: secret-server
          env:
            - name: REDIS_HOST
              value: "127.0.0.1:6379"
            - name: HTTP_DOCS_DIR
              value: "/bin/api/swagger/"
          image: wp-atrd-task
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi
      imagePullSecrets:
        - name: secret-server
      restartPolicy: Always
